Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/MethodLength:
  Max: 40
Metrics/BlockLength:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 15
Metrics/LineLength:
  Max: 120
Metrics/ModuleLength:
  Max: 165
Lint/RescueWithoutErrorClass:
  Enabled: false
  Max: 160
