#!/bin/bash

set -ex

touch /var/lib/mysql/*/* /var/lib/mysql/*

service mysql start

mysql -e "GRANT ALL PRIVILEGES ON *.* TO user@'%' IDENTIFIED BY 'user'"
mysql -e "CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;"

bundle exec rake db:migrate

bundle exec rspec
